logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
#  profiles:
    #运行的环境
#    active: my-prod
  application:
    name: atp
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master_01:
          url: jdbc:mysql://10.20.30.112:33063/atp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
            connection-test-query: SELECT 1
        master_02:
          url: jdbc:mysql://10.20.30.113:33063/atp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
            connection-test-query: SELECT 1
        master_03:
          url: jdbc:mysql://10.20.30.114:33063/atp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
            connection-test-query: SELECT 1
  security:
    enabled: true
    csrfEnabled: true
    username: admin
    password: Xms+kvR3Q+JnEGP37QSRlkSdiooAuumETfmbvSAISEvty4XVwSFHsFe/o6nNunXEtVjPhgwS7vkuYBSfp/+O+KTw/LqV73dY5/oDMU/3RxrQHagJbTiq++x9qUnQD8XCw/BkmdiDF4T4ceAKsRXiwfWtYzYLtGNbeY2UjfbvZsE=
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      write-dates-as-timestamps: true
server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /atp
    session:
      timeout: 60m
app:
  config:
    config-with-file-mode-enable: false


